### ISSUE TITLE
Support null provider / null_resource

### ISSUE THREAD

**Issue by thumphries** [brendanhay/terrafomo#20]
https://github.com/terraform-providers/terraform-provider-null

`null_resource` has been useful as a way to run once-only provisioners via `local_exec` (we don't do this very often but it has been necessary for bootstrapping EKS auth)

Have written some manual code for this but also seems like it might fit into `terrafomo-builtins`.

Would be happy to do this work, just unsure if you'd rather generate it or have it written by hand.

**Comment by brendanhay** [comment]
*mumble* *mumble* _ignition_ *mumble*
