### ISSUE TITLE
Provisioners

### ISSUE THREAD

**Issue by thumphries** [brendanhay/terrafomo#21]
Direct support for provisioners like `local_exec` would be quite useful. We're bolting this onto our stale fork at the moment.

**Comment by brendanhay** [comment]
I'll add the concept of provisioners to the internal Schema/Resource representation.

**Comment by thumphries** [comment]
Here's our shit implementation (against old HEAD) in case that's helpful https://github.com/FormationAI/terrafomo/commit/c1701f4c3ff891352ce95b066df9e7377e7bc97a

**Comment by brendanhay** [comment]
_mumble_ _ignition_ _mumble_

**Comment by brendanhay** [comment]
Provisioners and connections are now in `HEAD`.
